name: Docker Image

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - main

jobs:
  build-and-push-docker-image:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Build image
        run: make image

      - name: Push image
        env:
          CR_PAT: ${{ secrets.CR_PAT }}
        run: make push-to-ghcr
